twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        auth: '@App\Services\User\Users'
        cache: '@App\Services\Cache\Cache'
